complete configure

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1,14 +1,42 @@
 #!/bin/sh
+
 usage () {
 cat<<EOF
-usage: configure [ -h | -g ]
+usage: configure [ <option> ... ]
+
+where '<option>' is one of the following
+
+   -c    enable assertion checking (implied by '-g')
+   -g    debugging build (implies '-s' and '-c')
+   -h    print usage information
+   -s    compile with symbols  (implied by '-g')
 EOF
 }
+
+check=unknown
 debug=no
+symbols=unknown
+
 while [ $# -gt 0 ]
 do
-  -h) usage; exit 0;;
-  -g) debug=yes;;
-  *) echo "configure: error: invalid option '$1'" 1>&2; exit 1;;
+  case $1 in
+    -c) check=yes;;
+    -g) debug=yes;;
+    -h) usage; exit 0;;
+    -s) symbols=yes;;
+    *) echo "configure: error: invalid option '$1'" 1>&2; exit 1;;
+  esac
   shift
 done
+
+COMPILE="gcc -Wall"
+
+[ $check = unknown ] && check=$debug
+[ $symbols = unknown ] && symbols=$debug
+
+[ $symbols = yes ] && COMPILE="$COMPILE -g"
+[ $debug = no ] && COMPILE="$COMPILE -O3"
+[ $check = no ] && COMPILE="$COMPILE -DNDEBUG"
+
+echo "configure: $COMPILE"
+sed -e "s#@COMPILE@#$COMPILED#" makefile.in > makefile
